<!-- START of: finna - content/about_finna_sv.phtml -->

<?php $this->headTitle($this->translate('Finna - en helhet bestående av söktjänster')); $this->content()->setHeading($this->translate('Finna - en helhet bestående av söktjänster'));  ?>
<p>Finna är ett hem för miljontals exemplar av kultur- och vetenskapsmaterial i Finland.</p>
<p>Inhemska aktörer, såsom arkiv, bibliotek och museer, bidrar med unikt innehåll till Finna.</p>
<p>Nationalbiblioteket administrerar och utvecklar kontinuerligt tjänsten i samarbete med arkiv, bibliotek och museer samt övriga samarbetspartner.</p>
<p>Vårt mål är att göra det lätt att hitta och använda information samt så lätt och tryggt som möjligt att lära sig nytt.</p>
<h2>Vilken är skillnaden mellan Finna.fi och övriga Finna-söktjänster?</h2>
<p>Finna utgörs av Finna.fi som samlar material och hundratals andra Finna-söktjänster.</p>
<div class="finna-aboutfinna-panel panel ">
    <div class="panel-body">
        <h3>Finna.fi</h3>
        <p>I Finna.fi hittar du alla Finna-aktörers material på en och samma plats.</p>
        <p><a class="btn btn-primary" href="https://www.finna.fi/Content/about_finnafi">Läs mer</a></p>
    </div>
</div>
<div class="finna-aboutfinna-panel panel">
    <div class="panel-body">
        <h3>Övriga Finna-söktjänster</h3>
        <p>Inom de övriga Finna-tjänsterna ligger fokus på arkiven hos vissa materialleverantörer.</p>
        <p>I arkivens, bibliotekens och museernas egna söktjänster kan du bekanta dig med exempelvis olika urval i samlingarna hos vissa materialleverantörer. Högskolornas söktjänster erbjuder studenter och personal öppna material och licensbelagda e-material.</p>
        <p>I listan nedan kan du se vilka högskolor som har en egen Finna-söktjänst.</p>
        <ul class="finna-aboutfinna-nav nav">
            <li role="presentation" ><a href="#archives"><?=$this->translate('Archives') ?></a></li>
            <li role="presentation" ><a href="#museums"><?=$this->translate('Museums') ?></a></li>
            <li role="presentation" ><a href="#polylib"><?=$this->translate('Polytechnic Libraries') ?></a></li>
            <li role="presentation" ><a href="#speciallib"><?=$this->translate('Special libraries') ?></a></li>
            <li role="presentation" ><a href="#jointlib"><?=$this->translate('Joint libraries') ?></a></li>
            <li role="presentation" ><a href="#publiclib"><?=$this->translate('Public Libraries') ?></a></li>
            <li role="presentation" ><a href="#univlib"><?=$this->translate('University Libraries') ?></a></li>
            <li role="presentation" ><a href="#regionallib"><?=$this->translate('Regional views') ?></a></li>
        </ul>
        <?=$this->render('content/about_finna_sites.phtml') ?>
    </div>
</div>

<!-- END of: finna - content/about_finna_sv.phtml -->
