
<!-- START of: finna - RecordDriver/DefaultRecord/external-interface-link.phtml -->
<div class="external-interface-link">
  <a role="button" class="btn btn-primary" href="<?=$this->escapeHtmlAttr($this->link)?>" target="_blank">
   <?=$this->escapeHtmlAttr($this->translate('title_hold_place'))?> (<?=$this->escapeHtmlAttr($this->translate('external_link'))?>) <span class="sr-only">(<?=$this->escapeHtmlAttr($this->translate('Open in a new window'))?>)</span>
  </a>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/external-interface-link.phtml -->